# Generated by Django 5.0.1 on 2024-01-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='trim',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo_url',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
